/*
* generated by Xtext
*/
package de.abg.jreichert.ui.contentassist;

import de.abg.jreichert.ui.contentassist.AbstractMisterWongDslProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class MisterWongDslProposalProvider extends AbstractMisterWongDslProposalProvider {

}
