/*
* generated by Xtext
*/
package de.abg.jreichert.ui.contentassist;

import de.abg.jreichert.ui.contentassist.AbstractOperaDSLProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class OperaDSLProposalProvider extends AbstractOperaDSLProposalProvider {

}
