/*
 * generated by Xtext
 */
package de.abg.jreichert.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.syntaxcoloring.DefaultHighlightingConfiguration;
import org.eclipse.xtext.ui.editor.syntaxcoloring.ISemanticHighlightingCalculator;

import com.google.inject.Binder;

import de.abg.jreichert.ui.highlighting.WongHighlightingConfiguration;
import de.abg.jreichert.ui.highlighting.WongSemanticHighlightingCalculator;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MisterWongDslUiModule extends de.abg.jreichert.ui.AbstractMisterWongDslUiModule {

    public MisterWongDslUiModule(AbstractUIPlugin plugin) {
        super(plugin);
    }

    @Override
    public void configure(Binder binder) {
        super.configure(binder);
    }

    public Class<? extends ISemanticHighlightingCalculator> bindSemanticHighlightingCalculator() {
        return WongSemanticHighlightingCalculator.class;
    }

    public Class<? extends DefaultHighlightingConfiguration> bindHighlightingConfiguration() {
        return WongHighlightingConfiguration.class;
    }
}
