/*
* generated by Xtext
*/
package de.abg.jreichert.ui.labeling;

import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;

import com.google.inject.Inject;

import de.abg.jreichert.operaDSL.BookmarkFile;
import de.abg.jreichert.operaDSL.Folder;
import de.abg.jreichert.operaDSL.Link;

/**
 * Provides labels for a EObjects.
 * 
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#labelProvider
 */
public class OperaDSLLabelProvider extends DefaultEObjectLabelProvider {

	@Inject
	public OperaDSLLabelProvider(AdapterFactoryLabelProvider delegate) {
		super(delegate);
	}
	
	String text(BookmarkFile ele) {
		return ele.eResource().getURI().lastSegment();
	}

	String text(Folder ele) {
		return ele.getName();
	}
	
	String text(Link ele) {
		return ele.getName();
	}

	String image(BookmarkFile ele) {
		return "opera.png";
	}

	String image(Folder ele) {
		return "sample.gif";
	}	
	
	String image(Link ele) {
		return "opera.png";
	}	
}
