/*
 * generated by Xtext
 */
package de.abg.jreichert;

import org.eclipse.xtext.conversion.IValueConverterService;

import de.abg.jreichert.conversion.MisterWongValueConverterService;

/**
 * Use this class to register components to be used at runtime / without the
 * Equinox extension registry.
 */
public class MisterWongDslRuntimeModule extends
		de.abg.jreichert.AbstractMisterWongDslRuntimeModule {

	@Override
	public Class<? extends IValueConverterService> bindIValueConverterService() {
		return MisterWongValueConverterService.class;
	}
}
